config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home' => 'home#index'
  get 'contact' => 'home#contact'
  get 'refer' => 'home#refer'
  
  resources :home
  devise_for :admins
  devise_for :customers
  devise_for :accountants
  resources :accounts
  namespace :admin do
    # resources :dashboard
    resources :admins
    resources :customers
    resources :accountants
    get 'dashboard' => 'dashboard#index'
  end

  namespace :customer do
    resources :accounts
    resources :customers
    resources :customer_accountants
    get 'dashboard' => 'dashboard#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def contact;end

  def refer;end 

  def customer_dashboard 
  end

  def account_dashboard
   @accounts = Account.all   
   @customers = Customer.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div class="col-sm-12 top">
  <div class="container card">
    <div class="row">
      <!-- <div class="col-sm-2"></div> -->
      <div class="col-sm-6" style="margin-top: 1%">
        <iframe width="100%" height="380" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=taxvista&amp;&#10;                    aq=&amp;sll=37.0625,-95.677068&amp;sspn=57.510723,109.160156&amp;ie=UTF8&amp;hq=taxvista&amp;&#10;                    hnear=&amp;ll=37.489916,-121.926543&amp;spn=57.510723,109.160156&amp;t=m&amp;z=10&amp;iwloc=A&amp;&#10;                    cid=15359765648070471443&amp;output=embed" class="card-body">
        </iframe>
      </div>
      <div class="col-sm-1"><div class="vl"></div></div>
      <div class="col-sm-5" style="margin-top: 2%">
        <h2>Contact Us</h2>
        <h3 class="contact-text card-body">
          <p><b>Fremont Address:</b>194 Francisco Lane, #108, Fremont, CA 94539 <br>(Mission Blvd &amp; Warm springs, in the Safeway complex)<br><br></p>
          <p><b>Sunnyvale Address:</b>830 Stewart Dr, Sunnyvale, CA 94085 <br><br></p>
          <p><b>Phone:</b>408-508-4829</p><br>
          <!-- <p><b>Contact Hours:</b><br>Weekdays: 6 pm-9 pm<br>Weekends: 10 am - 9 pm</p><br> -->
          <p><b>Contact Hours:</b><br>Weekdays: 10am-9pm<br>Weekends: 10am-9pm</p><br>
        </h3>
        <br class="clear">
      </div>
    </div>
  </div>
</div>

app/views/home/customer_dashboard.html.erb
<div class="container">
  <% if customer_signed_in? %> 
    <div class="container-fluid">
      <%= link_to('Your Profile', edit_customer_registration_path) %>
    </div> 
  <% elsif accountant_signed_in? %>
    <div class="container">
      <div id="show" class="card">
        <div class="card-body">
          <p>
            <strong>First Name:</strong>
            <%= @customer.try(:first_name) %>
          </p>
          <p>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<header>     
	<div id="demo" class="carousel slide" data-ride="carousel" style="width: 100%; height: 500px">
		<!-- Indicators -->
		<ul class="carousel-indicators">
			<li data-target="#demo" data-slide-to="0" class="active"></li>
			<li data-target="#demo" data-slide-to="1"></li>
			<li data-target="#demo" data-slide-to="2"></li>
		</ul>

		<!-- The slideshow -->
		<div class="carousel-inner">
			<div class="carousel-item active">
				<%= image_tag 'tax-planning',style:"width:100%; height:500px " %>
			</div>
			<div class="carousel-item">
				<%= image_tag 'stefan', style:"width:100%; height:500px "%>
			</div>
			<div class="carousel-item">
				<%= image_tag 'nik',style:"width:100%; height:500px ", class: 'img-fluid' %>
			</div>
		</div>

		<!-- Left and right controls -->
		<a class="carousel-control-prev" href="#demo" data-slide="prev">
			<span class="carousel-control-prev-icon"></span>
		</a>
		<a class="carousel-control-next" href="#demo" data-slide="next">
			<span class="carousel-control-next-icon"></span>
		</a>
	</div>
</header>
<br class="clear" />
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<a href="#"><%= image_tag 'logo6',style:"width:100%; height:360px "%></a>
		</div>
		<div class="col-md-6">
			<div class="fl_right">
				<h2 class="innerfornt" >Get your biggest refund</h2>
				<h3 class="contact-text">
					<p class="innerfornt" align="left">
						<b style="color: green">Tax reform</b><br>
						The largest tax bill in 30 years has been signed. We will help you plan your 2018 financials based on your 2017 return.
					</p>
					<br>
					<p class="innerfornt" align="justify">
						<b style="color: green">Protect your identity</b><br>
						We don't outsource our work to an offshore location. Your data is in US and we work 100% from our US based location.
					</p>
					<br>
					<p class="innerfornt" align="left">
						<b style="color: green">IRS Certified Acceptance Agent</b><br>
						As IRS Certified Acceptance Agent for ITIN processing, we are authorized to process ITINs for both your spouse and kids from our office without the need to visit IRS office.
					</p>
					<br> <p style="color: green">Guaranteed low price, or we will do your return for free.</p>
				</h3>
			</div>
			<br class="clear" />
		</div>
	</div>
</div>

app/views/home/refer.html.erb
<div class="container card">
	<div class="row left-row">
		<div class="col-sm-4">
			<%= image_tag 'refer_banner5', class: 'refer-image'%>
		</div>
		<div class="col-sm-8 card-body">
			<div id="fl_right">
				<span><p class="for-a-limited-time">&nbsp;&nbsp;&nbsp;FOR A LIMITED TIME</p></span>
				<span><p class="give-your-friends">&nbsp;&nbsp;&nbsp;Give your friends 10% off, and you earn $20 cash for each referral.</p></span>
			</div>
			
			<div class="form-top">
				<form>
					<label class="label">Friend's Email Address: </label><br>
					<textarea required class="textarea" rows="4" cols="45" name="referral[referral_emails]" placeholder="Enter your friend's Email Addresses separated by a comma here"></textarea>
					<input type="submit" class="button refer-button" style="" value="Submit">
				</form>      
			</div>

			<div class="referrals-must-complete">
				<span><p>&nbsp;&nbsp;&nbsp;*Referrals must complete filling their Tax return with TaxVista before 3/30/2017.</p></span>
				<span><p style="margin-top: -2%;">&nbsp;&nbsp;&nbsp;Referral cash will be processed at the earliest or before April 25 2018.</p></span>
			</div>
		</div>
	</div>
	<br class="clear" />
</div>