config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home' => 'home#index'
  get 'contact' => 'home#contact'
  get 'refer' => 'home#refer'
  
  resources :home
  devise_for :admins
  devise_for :customers
  devise_for :accountants
  resources :accounts
  namespace :admin do
    # resources :dashboard
    resources :admins
    resources :customers
    resources :accountants
    get 'dashboard' => 'dashboard#index'
  end

  namespace :customer do
    resources :accounts
    resources :customers
    resources :customer_accountants
    get 'dashboard' => 'dashboard#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/admins/_form.html.erb
<div class="col-md-12">
  <div class="container">
    <div class="col-md-3"></div>
    <div class="col-md-6 card-body common-from">
      <%= form_with(model: [:admin, @admin], local: true) do |f| %>
      <% if admin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>
        <ul>
          <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div>
        <label>First Name</label>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>

      <div>
        <label>Last Name</label>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>

      <div>
        <label >Email Address </label>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div>
        <label>Password</label>
        <%= f.text_field :password, class: "form-control"%>
      </div>

      <div>
        <label>Password Confirmation</label>
        <%= f.text_field :password_confirmation, class: "form-control" %>
      </div><br>
      <div class="form-group text-center">
        <%= f.submit "create admin", :id => 'login', :class =>  'btn btn-primary' %>
        <%= link_to 'Cancel', admin_admins_path, :class =>  'btn btn-danger' %>
      </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<div class="container top">
  <h1 class="create-admin">Editing admin</h1><hr>
  <div class="form-admin">
    <%= render 'form', admin: @admin %>
    <%#= link_to 'Show',  [:admin, @admin] %>
    <%#= link_to 'Back', admin_admins_path %>
  </div>
</div>

app/views/admin/admins/index.html.erb
<div class="container-fluid">
  <h1  class="table-text-admins"> All admins</h1>
  <hr>
  <table id="example" class="table table-striped table-bordered table-admins">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
         <th>show</th>
        <th>edit</th>
        <th>delete</th>
      </tr>
    </thead>

    <tbody>
      <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.first_name %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Show', [:admin, admin], class: 'btn btn-primary'%></td>
         <td> <%= link_to 'Edit', [:edit, :admin, admin], class: 'btn btn-success' %></td>
          <td><%= link_to 'Destroy',  [:admin, admin], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Admin ', new_admin_admin_path, class: 'table-button-admins btn btn-primary' %>
</div>

app/views/admin/admins/new.html.erb
<div class="container top" >
  <h1 class="create-admin">Create Admin</h1><hr>
  <div class="form-admin">
    <%= render 'form', admin: @admin %>
  </div>
</div>

app/views/admin/admins/show.html.erb
<div class="container">
  <div id="show" class="card">
    <div class="card-body">
      <p>
        <strong>First Name:</strong>
        <%= @admin.first_name %>
      </p>
      <p>
        <strong>Last Name:</strong>
        <%= @admin.last_name%>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @admin.email%>
      </p>
      
      <%= link_to 'Back', admin_admins_path, class: 'btn btn-primary' %></a> |
      <%= link_to 'Edit',[:edit, :admin, @admin], class: 'btn btn-success' %>  </a>
    </div>
  </div>
</div>